blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('blogs/', include('blogs.urls')),
    path('admin/', admin.site.urls),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

blogs/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Blogs"
    

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blogs/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Blogs

# Create your views here.
def index(request): 

    posts = Blogs.objects.order_by('-created_at')[:10]

    context = {
        'posts' : posts
    }

    return render(request, 'blogs/index.html', context)

# Details Posts
def detail(request, post_id):
    try:
        post = Blogs.objects.get(pk=post_id)
    except Blogs.DoesNotExist:
        raise Http404("Questions does not exist")
    return render(request, 'blogs/detail.html', { 'post': post })

pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice

# Get questions and display them
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Show specific questions and choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Questions does not exist")
    return render(request, 'polls/detail.html', { 'question': question })

# Get questions and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', { 'question': question })

# Vote for a question choice
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Election Poll {% block title %}{% endblock %}</title>
</head>
<body>
    <!-- NavBar -->
    {% include 'partials/_navbar.html' %}
    <div class="conatiner">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    
</body>
</html>

templates/blogs/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card text-center">
    <div class="card-body">  
        <h5 class="card-title text-success">{{post.title}}</h5>
        <p class="card-text">{{post.body}}</p>
        <p class="text-muted">{{post.created_at}}</p>
        <a href="{% url 'blogs:index' %}" class="card-link btn btn-dark btn-sm">Go Back</a>
    </div>
</div>
{% endblock %}

templates/blogs/index.html
{% extends 'base.html' %}
{% block content %}
<div class="card text-center">
    <div class="card-body">
        <h1>Latest Blogs</h1>
        <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item"><a href="{% url 'blogs:detail' post.id %}">{{post.title}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
<div class="card text-center">
    <div class="card-body">
        <h1>Welcome To Election Poll</h1>
        <p>This is an example Django Polling App</p>
        <a href="{% url 'polls:index' %}" class="btn btn-dark">View Available Polls</a>
    </div>
</div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-dark mb-4 ml-auto">
    <div class="conatiner">
        <a class="navbar-brand" href="/">
          <img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
          Election Poll
        </a>
        <!-- <a href="/" class="navbar-brand">Election Poll</a> -->
        <a href="/blogs/" class="navbar-brand">Blog</a>
        <a href="/admin/" class="navbar-brand">Admin</a>
        
    </div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'polls:index' %}" class="btn btn-secondary btn-sm mb-3">Back to Polls</a>
<h1 class="text-center mb-3">{{ question.question_text }}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <div class="form-check">
        <input 
        type="radio"
        name="choice"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4" />
</form>

{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center mb-3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="lead">{{ question.question_text }}</p>
                    <a href="{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href="{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No Polls Available.</p>
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center mb-5">{{ question.question_text }}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }} vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:index' %}" class="btn btn-secondary">Back To Polls</a>
<a href="{% url 'polls:detail' question.id %}" class="btn btn-dark">Vote Again</a>
{% endblock %}